[agent]
  interval = "2s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "2s"
  flush_jitter = "0s"
  precision = ""

# Сбор метрик по всем запущенным контейнерам через Docker API
[[inputs.docker]]
  endpoint = "unix:///var/run/docker.sock"
  timeout = "5s"
  gather_services = false
  perdevice_include = ["cpu"]
  total_include = ["cpu", "blkio", "network"]

# Экспорт в формате Prometheus
[[outputs.prometheus_client]]
  listen = ":9273"
  metric_version = 2